# Generated by Django 4.1 on 2023-11-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdventNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(unique=True)),
                ("position_x", models.IntegerField()),
                ("position_y", models.IntegerField()),
            ],
        ),
    ]
