# Generated by Django 4.1 on 2023-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0002_adventnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_taken",
            field=models.BooleanField(default=False),
        ),
    ]
