# Generated by Django 4.1 on 2023-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0006_decision_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="snowballs",
            field=models.IntegerField(default=5),
        ),
    ]
