# Generated by Django 4.1 on 2023-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0008_ornament_gift"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="hits_received",
            field=models.IntegerField(default=0),
        ),
    ]
