# Generated by Django 4.1 on 2023-11-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0009_character_hits_received"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="hits_received",
        ),
        migrations.CreateModel(
            name="SnowballHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attacker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacks_made",
                        to="adventApp.character",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits_received",
                        to="adventApp.character",
                    ),
                ),
            ],
        ),
    ]
