# Generated by Django 4.1 on 2023-11-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0013_bild_notizzettel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tagesnachricht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.IntegerField(unique=True)),
                ("nachricht", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="bild",
            name="tag",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notizzettel",
            name="tag",
            field=models.IntegerField(default=0),
        ),
    ]
