# Generated by Django 4.1 on 2023-11-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0014_tagesnachricht_bild_tag_notizzettel_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="bild",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bild_character",
                to="adventApp.character",
            ),
        ),
        migrations.AddField(
            model_name="notizzettel",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notizzettel_character",
                to="adventApp.character",
            ),
        ),
    ]
