# Generated by Django 4.1 on 2023-11-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0015_bild_character_notizzettel_character"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labyrinth",
            old_name="next_decision_a",
            new_name="next_labyrinth_a",
        ),
        migrations.RenameField(
            model_name="labyrinth",
            old_name="next_decision_b",
            new_name="next_labyrinth_b",
        ),
        migrations.RemoveField(
            model_name="labyrinth",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="labyrinth",
            name="background_image",
            field=models.ImageField(upload_to="labyrinths/"),
        ),
        migrations.CreateModel(
            name="Vote_lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(max_length=100)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adventApp.character",
                    ),
                ),
                (
                    "labyrinth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adventApp.labyrinth",
                    ),
                ),
            ],
        ),
    ]
