# Generated by Django 4.1 on 2023-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "adventApp",
            "0016_rename_next_decision_a_labyrinth_next_labyrinth_a_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="labyrinth",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
