# Generated by Django 4.1 on 2023-11-30 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("adventApp", "0017_labyrinth_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labyrinth",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
